### ISSUE TITLE
Issue Closed - Application runs on Android version 4.0.3

### ISSUE THREAD

**Issue by ajaybarvey** [StevenByle/Android-Phone-Tablet-Example#1]
Thanks for sharing this demo which is very helpful to understand how to design for tablet. Although the minSdkVersion is set to 11 the application does not run on Sony Tablet with android version 4.0.3 nor on mobile with android version 4.4.2. What could be the issue?

**Comment by StevenByle** [comment]
Could you be more specific when you say "does not run"? Are you able to install the app, is it crashing (if so, is there a log), is it not compiling, etc? This was written 3 years ago in Eclipse (no longer officially supported by Google), and would need to be updated to run in Android Studio. The code itself should be fine, it's just the project setup that would need to be ported.

**Comment by ajaybarvey** [comment]
Steven,
Thanks for the reply and my apologies for the false alarm. The issue was with ADB driver for the tablet and once the driver was fixed it works fine. I have the project ported to Android Studio and it works fine.
